---
title: Finding images with permissions to use
hero_image: images/banner.png
description: How to find digital images you have permission to use
theme: red
duration: 2
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Finding images with permissions to use
