---
title: Afbeeldingen zoeken met machtigingen om ze te gebruiken
hero_image: images/banner.png
description: Hoe je digitale afbeeldingen kunt vinden die je mag gebruiken
theme: rood #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Afbeeldingen zoeken met machtigingen om ze te gebruiken
