---
title: Pronalaženje slika s dozvolom za upotrebu
hero_image: images/banner.png
description: Kako pronaći digitalne slike za koje imate dozvolu za upotrebu
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: Pronalaženje slika s dozvolom za upotrebu
