---
title: Encontrar im치genes con permisos para ser usadas
hero_image: images/banner.png
description: C칩mo encontrar im치genes digitales que tienen permisos para ser usadas
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: Encontrar im치genes con permisos para ser usadas
