---
title: Suchen von Bildern mit Verwendungsberechtigungen
hero_image: images/banner.png
description: So findet man digitale Bilder, zu deren Verwendung man berechtigt ist
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - title: Suchen von Bildern mit Verwendungsrecht
