---
title: Encontrando imagens com permissões para usar
hero_image: images/banner.png
description: Como encontrar imagens digitais que você tem permissão para usar
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum:
interests:
technologies:
site_areas:
steps:
  - 
    title: Encontrando imagens com permissões para usar
